### ISSUE TITLE
Add Bear

### ISSUE THREAD

**Issue by zenorocha** [dracula/dracula.github.io#53]
http://www.bear-writer.com/

**Comment by caarlos0** [comment]
I think this is fixed? There is a dracula theme on bear:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/245435/66707153-9ebea800-ed12-11e9-949e-9bb89dc5dd69.png">

**Comment by zenorocha** [comment]
Yeah, we just have to add a page on the website to promote that.

**Comment by zenorocha** [comment]
This is finally live: https://draculatheme.com/bear 🐻
