### ISSUE TITLE
Please don't block Tor users

### ISSUE THREAD

**Issue by TrashMacNugget** [dracula/dracula.github.io#59]
The site uses Cloudflare, which by default will force Tor users to complete a CAPTCHA (which does not work without JavaScript). Please consider disabling forcing Tor users to complete CAPTCHAs just to see your site.

[This article explains how to disable this behavior.](https://support.cloudflare.com/hc/en-us/articles/203306930-Does-Cloudflare-block-Tor-)

Thanks for the great theme!

**Comment by hacknug** [comment]
Planning on rebuilding the site using Gridsome or Gatsby and host it on Netlify at some point in the near future.

Would that solve your issue?

**Comment by Glennmen** [comment]
@hacknug That won't change anything if you are still using Cloudflare firewall in front of your site. There is a setting in the Cloudflare dashboard to enable `Onion Routing`.

**Comment by hacknug** [comment]
Perfect! Will ask @zenorocha for access to the Cloudflare panel and I'll look into it. Thanks for the info!

**Comment by hacknug** [comment]
@TrashMacNugget could you check if anything changed and is any better? Zeno told me he changed the TOR settings on Cloudflare.
