### ISSUE TITLE
Add a list to show all supported Apps in additon to Featured

### ISSUE THREAD

**Issue by xukai92** [dracula/dracula.github.io#61]
Will it be a nice idea? Maybe just a script to pull the complete list from https://github.com/dracula somehow. Otherwise people might think there is no Dracula theme beyond the current listed Apps. 

Related issue: https://github.com/dracula/termite/issues/1

**Comment by zenorocha** [comment]
Here's a PR that includes termite: https://github.com/dracula/dracula.github.io/pull/67

I can merge it as soon as I have the instructions to activate the theme.
