### ISSUE TITLE
Outdated documentation on production website

### ISSUE THREAD

**Issue by screendriver** [dracula/dracula.github.io#64]
If you visit the official website of [Dracula for Hyper](https://draculatheme.com/hyper/) you can see

![1217941b-0040-4579-9ec0-f3c4e80975d8](https://user-images.githubusercontent.com/149248/46272338-e4b62d00-c550-11e8-877a-6d1aa121ec19.png)

But the [source code](https://github.com/dracula/dracula.github.io/blob/site/src/content/hyper/index.html) in this repo is already updated since April to use `hyper` instead of `hpm`.

@dangvanthanh @zenorocha

**Comment by dangvanthanh** [comment]
It resolve in #58. Waiting @zenorocha merge code.

**Comment by screendriver** [comment]
It is already merged since 5 months. So that mean that there was no site publish in the last 5 months?

**Comment by dangvanthanh** [comment]
I was PR for waiting @zenorocha approved publish new outdated document.

**Comment by zenorocha** [comment]
It should be fixed now, sorry for the inconvenience @screendriver and thanks a lot for the PR @dangvanthanh!
