### ISSUE TITLE
Migration to Next.js

### ISSUE THREAD

**Issue by zenorocha** [dracula/dracula.github.io#96]
Hello everyone,

We're migrating the site from [Metalsmith](https://metalsmith.io/) to [Next.js](https://nextjs.org/). 

Before this goes live, we would like to get your feedback.

## What problems are we solving with this release?

* Removes technical debt since Metalsmith is no longer maintained
* Moves the install instructions from the site to theme each repository ([see example](https://github.com/dracula/vim/blob/master/INSTALL.md))
* Moves the screenshots from the site to each theme repository ([see example](https://github.com/dracula/vim/blob/master/screenshot.png))
* Fixes the fetching of GitHub contributors which was broken after the WeDeploy shutdown

## What problems are we *not* solving with this release?

* The overall design has not been updated
* The landing page is not dinamically generated
* The theme icons and colors are still manually defined

## Want to see for yourself?

Clone the [3.x](https://github.com/dracula/dracula.github.io/tree/3.x) branch and follow the instructions on the `README`.

If you're curious, you can see the full commit here: https://github.com/dracula/dracula.github.io/commit/46c42a7f46ae35684ed9e835e36a7c7108715d6c

@dracula/maintainers

**Comment by benknoble** [comment]
Just to clarify—not dynamically generated means the landing page only? The instructions will now be fetched from each repo, so, e.g., if (when) we update the vim instructions, the side will reflect that update?

Or will we still have to go through the process where we ask for a re-deploy to get the new instructions onto the site?

**Comment by zenorocha** [comment]
What I meant is that every theme page is dynamically generated (see `[theme.js]`) and the landing page is hard-coded with each theme link.

In terms of the instructions being fetched from the repo, we would still need to go through a process of updating the site :/

The GitHub API has a limit of requests (5000 per hour) and to avoid hitting this limit we would have the site static exported on build time.

**Comment by oswaldoacauan** [comment]
GitHub Actions to trigger a rebuild/deploy each time a PR is merged? 🙃

**Comment by zenorocha** [comment]
I like that @oswaldoacauan!

**Comment by benknoble** [comment]
@oswaldoacauan yes please! Anything to avoid the discrepancy between a repo and the site; have the installation issues we get are because of this

**Comment by zenorocha** [comment]
Since you're all liking the current state, I deployed the `3.x` branch to production so we can start feeling this new version for real.

**Comment by zenorocha** [comment]
Merged to `site` branch and now live on draculatheme.com.

**Comment by benknoble** [comment]
So, just to continue to clarify, I updated the vim screenshot, and draculatheme.com/vim has been updated with the correct screenshot. How did that happen? I didn't do it, that I'm aware of.

**Comment by zenorocha** [comment]
I made a deployment yesterday night. It was a coincidence, the automation has not been set up yet.

**Comment by zenorocha** [comment]
Ohh, I see that it was merged 3 hours ago, so let me clarify.

The screenshots are always fetched directly from the master branch, so regardless of deploying a new version of the site or not, it will always be the latest.

https://github.com/dracula/dracula.github.io/blob/site/pages/%5Btheme%5D.js#L42

Only the contributor list and the install instructions will depend on a new deployment of the site.
