### ISSUE TITLE
Duplicated content

### ISSUE THREAD

**Issue by netojose** [dracula/dracula.github.io#98]
**Visual Studio** Code appears twice on the home page

<img width="1731" alt="Screenshot 2020-01-03 at 00 33 34" src="https://user-images.githubusercontent.com/134008/71701339-c75db780-2dc0-11ea-92c6-f83e05a2dbee.png">

**Comment by zenorocha** [comment]
That's actually on purpose ;) The first line is "Featured", which is a collection of popular themes that are trending now.
